//! # Introduction
//! 
//! ## nightly 
//!
//! <https://wtfm-rs.github.io/nightly>
//!
//!
//!

/// Default code code generated by `cargo new --lib`
///
/// We can test it in 
/// [nightly Rust playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024).
///
/// ```
/// fn add(left: u64, right: u64) -> u64 {
///    left + right
/// }
///
/// assert_eq!(add(2, 2), 4);
/// ```
pub fn add(left: u64, right: u64) -> u64 {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
